### ISSUE TITLE
initialization of aspect category weights

### ISSUE THREAD

**Issue by sricinu** [Raghu150999/UnsupervisedABSA#5]
Thank you for the wonderful project

curious to know how you initilaized the weights for the aspect categories

        self.aspect_weights = [345, 67, 201] # aspect category distribution (restaurant)
        self.sentiment_weights = [231, 382] # sentiment category distribution (restaurant)

**Comment by Raghu150999** [comment]
These are just dataset distributions for aspect and sentiment class in the particular restaurant dataset. Code could have been more generic :)
